server.port=8081
spring.application.name=prescription-service

# MongoDB connection string
spring.data.mongodb.uri=mongodb://localhost:27017/pharma_db

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/