server.port=8082
spring.application.name=inventory-service

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.h2.console.enabled=true

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/